import Head from 'next/head';


export default function Home(): JSX.Element {


    return (
        <div>
            <Head>
                <title>Top-app</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <h1>Hello from Next!</h1>
            </main>
        </div>
    );
}
